version: "3.8"
services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.prod
        restart: unless-stopped
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        env_file:
            - ./api/.env
        environment:
            NODE_ENV: production
        restart: unless-stopped
    db:
        image: mongo
        volumes:
            - type: volume
              source: dbprod
              target: /data/db
        env_file:
            - ./db/.env
        restart: unless-stopped
    reverse-proxy:
        build:
            context: ./reverse-proxy
            dockerfile: Dockerfile.prod
        ports:
            - 80:80
        depends_on:
            - api
            - db
            - client
        restart: unless-stopped
volumes:
    dbprod:
        external: true 