version: "3.8"
services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - type: bind
              source: ./client
              target: /app
            - type: volume
              target: /app/node_modules
        ports:
            - 3000:3000
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        volumes:
            - type: bind
              source: ./api/src
              target: /app/src
        ports:
            - 3001:8000
    db:
        image: mongo
        volumes:
            - type: volume
              source: dbtest
              target: /data/db
    db-dashboard:
        image: mongo-express
        links:
            - db:mongo
        env_file:
            - ./db/.env
        ports:
            - 8081:8081
        depends_on:
            - db
    reverse-proxy:
        build:
            context: ./reverse-proxy
            dockerfile: Dockerfile.dev
        ports:
            - 80:80
        depends_on:
            - api
            - db
            - client
volumes:
    dbtest: 